package gamsa;

import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Properties;

import gamsa.population.Alignment;
import gamsa.population.Individual;
import gamsa.population.Sequence;
import gamsa.scorer.Blosum62Scorer;
import gamsa.scorer.DNAScorer;

import static java.lang.System.out;

/**
 * Sample problems to compare GAMSA to ClustalW
 * 
 * @author Amie Radenbaugh and Tom Austin
 */
public class TestCases
{
	//Scorers vary by problem, so we need to reset the scorer used through the InfoCenter.
	private static InfoCenter i_center = InfoCenter.getCenter();
	
	/**
	 * Select which test to run
	 */
	public static void main(String[] args) throws IOException
	{
		TestCases tester = new TestCases();
		MultiSeqAligner aligner = new MultiSeqAligner();
		String[] inputSequences = null;
		Alignment solution = null;
		
		out.println("Please select a test to run");
		out.println("  0) Amino Acid Test 1");
		out.println("  1) Amino Acid Test 2");		
		out.println("  2) DNA Mickey Mouse Sequences");
		out.println("  3) DNA MYH16 Sequences");
		out.println("  4) DNA Beta Globin Sequences");
		out.println("  5) DNA HIV Sequences");
		out.println("  6) DNA BRCA1 Sequences");
		int c = System.in.read();
		switch (c)
		{
			case '0':
			{
				i_center.setScorer(new Blosum62Scorer());				
				inputSequences = tester.getAAHemoGlobinSequences();
				solution = tester.getAAHemoGlobinClustalWSolution();
				break;
			}
			case '1':
			{
				i_center.setScorer(new Blosum62Scorer());				
				inputSequences = tester.getAAGrowthHormoneSequences();
				solution = tester.getAAGrowthHormoneClustalWSolution();
				break;
			}			
			case '2':
			{
				i_center.setScorer(new DNAScorer());				
				inputSequences = tester.getDNAMickeyMouseSequences();
				solution = tester.getDNAMickeyMouseClustalWSolution();
				break;
			}			
			case '3':
			{
				i_center.setScorer(new DNAScorer());				
				inputSequences = tester.getDNAMYH16Sequences();
				solution = tester.getDNAMYH16ClustalWSolution();
				break;
			}
			case '4':
			{
				i_center.setScorer(new DNAScorer());				
				inputSequences = tester.getDNABetaGlobinSequences();
				solution = tester.getDNABetaGlobinClustalWSolution();
				break;
			}
			case '5':
			{
				i_center.setScorer(new DNAScorer());				
				inputSequences = tester.getDNAHIVSequences();
				solution = tester.getDNAHIVClustalWSolution();
				break;
			}
			case '6':
			{
				i_center.setScorer(new DNAScorer());				
				inputSequences = tester.getDNABRCA1Sequences();
				solution = tester.getDNABRCA1ClustalWSolution();
				break;
			}			
		}		
		
		long startTime = System.currentTimeMillis();		
		Individual best = aligner.findSolution(inputSequences);
		long endTime = System.currentTimeMillis();		
					
		Date date = new Date(endTime - startTime);
		SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss:SS");
		sdf.setTimeZone(new java.util.SimpleTimeZone(0, "UTC"));
		
		out.println("******");
		out.println("GAMSA Best " + best);
						 
		out.println();
		out.println("ClustalW Solution " + solution); 
		
		out.println();
		out.println("Statistics:");
		out.println("Time Elapsed (HH:mm:ss:SS): " + sdf.format(date));
		Properties properties = MultiSeqAligner.getDefaultProperties();
		out.println("Population Size: " + properties.getProperty("populationSize"));
		out.println("Number of Unchanged Rounds: " + properties.getProperty("unchangedRoundsNeeded"));
		out.println("Number of Total Rounds: " + aligner.getNumberOfRoundsExecuted());
		out.println("Goodbye, and thank you for flying GAMSA.");
		out.println("******");
	}
	
	public String[] getDNAMickeyMouseSequences()
	{		
		String s1 = "ATTGCCATT";
		String s2 = "ATGGCCATT";
		String s3 = "ATCCAATTTT";
		String s4 = "ATCTTCTT";
		String s5 = "ATT";
		String s6 = "GGCCAT";
		String s7 = "ATTG";
		
		String[] inputSequences = {s1, s2, s3, s4, s5, s6, s7};
		
		return inputSequences;
	}
	
	public Alignment getDNAMickeyMouseClustalWSolution()
	{		
		Alignment solution = new Alignment();
		solution.addSequence(new Sequence("ATCTTCTT--"));
		solution.addSequence(new Sequence("ATCCAATTTT"));
		solution.addSequence(new Sequence("ATT-------"));
		solution.addSequence(new Sequence("--GGCCAT--"));
		solution.addSequence(new Sequence("ATGGCCATT-"));
		solution.addSequence(new Sequence("ATTGCCATT-"));
		solution.addSequence(new Sequence("------ATTG"));
		return solution;
	}
	
	public String[] getDNAMYH16Sequences()
	{	
		//>gi|37222316|gb|AY350716.1|Lagothrix lagotricha (MYH16) gene, exon 18
		String s1 = "GAGCAGCTGAACAAGCTGATGACCACCCTCCACAGCACTGCACCCCATTTTGTCCGCTGTATTGTGCCCAATGAGTTTAAGCAGTCAG";

		//>gi|37222318|gb|AY350717.1| Macaca nemestrina (MYH16) gene, exon 18
		String s2 = "GAGCAGCTGAACAAGCTGATGACCACCCTCCATAGCACCGCACCCCATTTTGTCCGCTGTATTGTCCCCAATGAGTTTAAGCAATCGG";

		//>gi|37222320|gb|AY350718.1| Macaca mulatta (MYH16) gene, exon 18
		String s3 = "GAGCAGCTGAACAAGCTGATGACCACCCTCCATAGCACCGCACCCCATTTTGTCCGCTGTATTGTCCCCAATGAGTTTAAGCAATCGG";

		//>gi|37222322|gb|AY350719.1| Pongo pygmaeus (MYH16) gene, exon 18
		String s4 = "GAGCAGCTGAACAAGCTGATGACCACCCTCCATAGCACCGCACCCCATTTTGTCCGCTGTATTATCCCCAATGAGTTTAAGCAATCGG";

		//>gi|37222324|gb|AY350720.1| Gorilla gorilla (MYH16) gene, exon 18
		String s5 = "GAGCAGCTGAACAAGCTGATGACCACCCTCCATAGCACCGCACCCCATTTTGTCCGCTGTATTATCCCCAATGAGTTTAAGCAATCGG";

		//>gi|37222326|gb|AY350721.1| Pan paniscus (MYH16) gene, exon 18
		String s6 = "GAGCAGCTGAACAAGCTGATGACCACCCTCCATAGCACCGCACCCCATTTTGTCCGCTGTATTATCCCCAATGAGTTTAAGCAATCGG";

		//>gi|37222328|gb|AY350722.1| Pan troglodytes (MYH16) gene, exon 18
		String s7 = "GAGCAGCTGAACAAGCTGATGACCACCCTCCATAGCACCGCACCCCATTTTGTCCGCTGTATTATCCCCAATGAGTTTAAGCAATCGG";

		//>gi|45752610:36298-36383 TPA_exp: Homo sapiens (MYH16) pseudogene
		String s8 = "GAGCAGCTGAACAAGCTGATGACCACCCTCCATAGCCGCACCCCATTTTGTCCGCTGTATTATCCCCAATGAGTTTAAGCAATCGG";			
		
		String[] inputSequences = {s1, s2, s3, s4, s5, s6, s7, s8};
		
		return inputSequences;
	}
	
	public Alignment getDNAMYH16ClustalWSolution()
	{						                                
		Alignment solution = new Alignment();
		solution.addSequence(new Sequence("GAGCAGCTGAACAAGCTGATGACCACCCTCCATAGC--CGCACCCCATTTTGTCCGCTGTATTATCCCCAATGAGTTTAAGCAATCGG"));
		solution.addSequence(new Sequence("GAGCAGCTGAACAAGCTGATGACCACCCTCCATAGCACCGCACCCCATTTTGTCCGCTGTATTATCCCCAATGAGTTTAAGCAATCGG"));
		solution.addSequence(new Sequence("GAGCAGCTGAACAAGCTGATGACCACCCTCCATAGCACCGCACCCCATTTTGTCCGCTGTATTATCCCCAATGAGTTTAAGCAATCGG"));
		solution.addSequence(new Sequence("GAGCAGCTGAACAAGCTGATGACCACCCTCCATAGCACCGCACCCCATTTTGTCCGCTGTATTATCCCCAATGAGTTTAAGCAATCGG"));
		solution.addSequence(new Sequence("GAGCAGCTGAACAAGCTGATGACCACCCTCCATAGCACCGCACCCCATTTTGTCCGCTGTATTGTCCCCAATGAGTTTAAGCAATCGG"));
		solution.addSequence(new Sequence("GAGCAGCTGAACAAGCTGATGACCACCCTCCATAGCACCGCACCCCATTTTGTCCGCTGTATTGTCCCCAATGAGTTTAAGCAATCGG"));
		solution.addSequence(new Sequence("GAGCAGCTGAACAAGCTGATGACCACCCTCCACAGCACTGCACCCCATTTTGTCCGCTGTATTGTGCCCAATGAGTTTAAGCAGTCAG"));
		return solution;
	}
	
	public String[] getDNABetaGlobinSequences()
	{	
		//GBREFMAM:31982299 	Mus musculus hemoglobin, beta adult major chain (Hbb-b1), mRNA.
		String s1 = "GTTTACGTTTGCTTCTGATTCTGTTGTGTTGACTTGCAACCTCAGAAACAGACATCATGGTGCACCTGACTGATGCTGAGAAGGCTGCTGTCTCTGGCCTGTGGGGAAAGGTGAACGCCGATGAAGTTGGTGGTGAGGCCCTGGGCAGGC";
		//GBREFMAM:28302128 	Homo sapiens hemoglobin, beta (HBB), mRNA.
		String s2 = "ACATTTGCTTCTGACACAACTGTGTTCACTAGCAACCTCAAACAGACACCATGGTGCATCTGACTCCTGAGGAGAAGTCTGCCGTTACTGCCCTGTGGGGCAAGGTGAACGTGGATGAAGTTGGTGGTGAGGCCCTGGGCAGGC";
		//GBMAM:164148 		Goat beta-x-globin (psi-beta-x) pseudogene, complete cds with
		String s3 = "TAGGGCCCCTGCTGCTTACACCTGCTTTTGACACAACTTGCAGCTGGGTAAACACACATCATGGTGCATCTGACTCTAGAAGAGAAGGCTACTTGTCACTGCCCTGTGGAGCAAGATGAGGGTGGCTGAAGTTGGTGTTGAAACCCTAGGCAGGC";
		//GBMAM:165890 		Sheep (O.aries) beta-globin gene mRNA, 5' flank and first exon,
		String s4 = "ACACTTGCTTCTGACACACCGTGCTCACTAGCAGCTGCACAAACACACACCATGCTGACTGCTGAGGAGAAGGCTGCCGTCACCGGCTTCTGGGGCAAGGTGAAAGTGGATGAAGTTGGTGCTGAGGCCCTGGGCAGGT";
		//GBMAM:164284 		Opossum beta-hemoglobin beta-M gene, complete cds. 
		String s5 = "AGCTAGATTAGTTTCAGCATCATACTACTTTTGACACAGCTCTGTGTTCACAAGTAAACTTTCAAAATGGTGCACTTGACTTCTGAGGAGAAGAACTGCATCACTACCATCTGGTCTAAGGTGCAGGTTGACCAGACTGGTGGTGAGGCCCTTGGCAGGT";
				
		String[] inputSequences = {s1, s2, s3, s4, s5};
		
		return inputSequences;
	}
	
	public Alignment getDNABetaGlobinClustalWSolution()
	{						                                
		Alignment solution = new Alignment();
		solution.addSequence(new Sequence("GTTTACGTTTGCTTC----TGATTC----TGTTGTGTTGACT---TGCAACCTCAGAAACAGACATCATGGTGCACCTGACTGATGCTGAGAAGGCTGCT-GTCTCTGGCCTGTGGGGAAAGGTGAACGCCGATGAAGTTGGTGGTGAGGCCCTGGGCAGGC"));
		solution.addSequence(new Sequence("----ACATTTGCTTC----TGACAC----AACTGTGTTCACT---AGCAACCTC--AAACAGACACCATGGTGCATCTGACTCCTGAGGAGAAGTCTGCC-GTTACTGCCCTGTGGGGCAAGGTGAACGTGGATGAAGTTGGTGGTGAGGCCCTGGGCAGGC"));
		solution.addSequence(new Sequence("TAGGGCCCCTGCTGC----TTACACCTGCTTTTGACACAACT---TGCAGCTGGGTAAACACACATCATGGTGCATCTGACTCTAGAAGAGAAGGCTACTTGTCACTGCCCTGTGGAGCAAGATGAGGGTGGCTGAAGTTGGTGTTGAAACCCTAGGCAGGC"));
		solution.addSequence(new Sequence("----ACACTTGCTTC----TGACACACCGTGCTCAC-----T---AGCAGCTGCACAAACACACACCATG------CTGACTGCTGAGGAGAAGGCTGCC-GTCACCGGCTTCTGGGGCAAGGTGAAAGTGGATGAAGTTGGTGCTGAGGCCCTGGGCAGGT"));		
		solution.addSequence(new Sequence("AGCTAGATTAGTTTCAGCATCATAC-TACTTTTGACACAGCTCTGTGTTCACAAGTAAACTTTCAAAATGGTGCACTTGACTTCTGAGGAGAAGAACTGC-ATCACTACCATCTGGTCTAAGGTGCAGGTTGACCAGACTGGTGGTGAGGCCCTTGGCAGGT"));		
		return solution;
	}
	
	public String[] getDNAHIVSequences()
	{	
		//Homo sapiens Tar (HIV1) RNA binding protein 1 (TARBP1), mRNA.
		String s1 = "GAAGGAAATCAGATACATGTTATAAAGCCAGTTTTACCAAAGCTAAACAATCTGTTTGAATATGCGGTGTCAGAGGAAAATGGATGTTGGCTCTTTCACCCATCCTGGCATATGTGTATTTATAAAAGAATGTTTGAAAGTGAAAACAAAATCCTGTCCAAAGAAGGTGTTATCCATTTTTTGGAGCTGTATGAAACAAAGATTCTTCCATTTTCACCAGAATTTTCTGAGTTTATTATTGGACCATTAATGGATGCGCTTTCAGAGAGCTCTCTGTATAGCAGGTCCCCAGGCCAGCCAATAGGAAGCTGTTCTCCATTGGGACTGAAATTACAGAAGTTTTTAGTCACTTATATTTCTCTTCTTCCAGAAGAAATAAAGAGTAGCTTCCTATTGAAGTTTATTCGGAAGATGACAAGTAGGCATTGGTGTGCTGTTCCCATTTTGTTTCTATCTAAGGCTTTGGCAAATGTCCCAAGACATAAGGCCCTGGGTATAGATGGGCTTCTTGCTCTCAGGGATGTTATTCATTGCACTATGATCACACATCAGATTCTCCTGAGAGGGGCAGCCCAATGCTACCTTCTTCAAACAGCTATGAATTTGCTAGATGTGGAGAAAGTGTCACTTTCT";
		//Homo sapiens clone AD-14 HIV-1 integration site.
		String s2 = "GAAGGAAATCAGATACATGTTATAAAGCCAGTTTTACCAAAGCTAAACAATCTGTTTGAATATGCGGTGTCAGAGGAAAATGGATGTTGGCTCTTTCACCCATCCTGGCATATGTGTATTTATAAAAGAATGTTTGAAAGTGAAAACAAAATCCTGTCCAAAGAAGGTGTTATCCATTTTTTGGAGCTGTATGAAACAAAGATTCTTCCATTTTCACCAGAATTTTCTGAGTTTATTATTGGACCATTAATGGATGCGCTTTCAGAGAGCTCTCTGTATAGCAGGTCCCCAGGCCAGCCAATAGGAAGCTGTTCTCCATTGGGACTGAAATTACAGAAGTTTTTAGTCACTTATATTTCTCTTCTTCCAGAAGAAATAAAGAGTAGCTTCCTATTGAAGTTTATTCGGAAGATGACAAGTAGGCATTGGTGTGCTGTTCCCATTTTGTTTCTATCTAAGGCTTTGGCAAATGTCCCAAGACATAAGGCCCTGGGTATAGATGGGCTTCTTGCTCTCAGGGATGTTATTCATTGCACTATGATCACACATCAGATTCTCCTGAGAGGGGCAGCCCAATGCTACCTTCTTCAAACAGCTATGAATTTGCTAGATGTGGAGAAAGTGTCACTTTCT";
		//Homo sapiens HIV-1 Rev binding protein (HRB), mRNA.
		String s3 = "GACAGTCTAGTGGTTCGAGTAATTTTGGAGGTTTCCCCACAGCAAGTCACTCTCCTTTTCAGCCCCAAACTACAGGTGGAAGTGCTGCATCAGTAAATGCTAATTTTGCTCATTTTGATAACTTCCCCAAATCCTCCAGTGCTGATTTTGGAACCTTCAATACTTCCCAGAGTCATCAAACAGCATCAGCTGTTAGTAAAGTTTCAACGAACAAAGCTGGTTTACAGACTGCAGACAAATATGCAGCACTTGCTAATTTAGACAATATCTTCAGTGCCGGGCAAGGTGGTGATCAGGGAAGTGGCTTTGGGACCACAGGTAAAGCTCCTGTTGGTTCTGTGGTTTCAGTTCCCAGTCAGTCAAGTGCATCTTCAGACAAGTATGCAGCTCTGGCAGAACTAGACAGCGTTTTCAGTTCTGCAGCCACCTCCAGTAATGCGTATACTTCCACAAGTAATGCTAGCAGCAATGTTTTTGGAACAGTGCCAGTGGTTGCTTCTGCACAGACACAGCCTGCTTCATCAAGTGTGCCTGCTCCATTTGGAGCTACGCCTTCCACAAATCCATTTGTTGCTGCTGCTGGTCCTTCTGTGGCATCTTCTACAAACCCAT";
		//Homo sapiens Tar (HIV-1) RNA binding protein 2 (TARBP2), transcript
		String s4 = "GCGACACCAGCTGCACTGGTCAGGGCCCCAGCAAGAAGGCAGCCAAGCACAAGGCAGCTGAGGTGGCCCTCAAACACCTCAAAGGGGGGAGCATGCTGGAGCCGGCCCTGGAGGACAGCAGTTCTTTTTCTCCCCTAGACTCTTCACTGCCTGAGGACATTCCGGTTTTTACTGCTGCAGCAGCTGCTACCCCAGTTCCATCTGTAGTCCTAACCAGGAGCCCCCCCATGGAACTGCAGCCCCCTGTCTCCCCTCAGCAGTCTGAGTGCAACCCCGTTGGTGCTCTGCAGGAGCTGGTGGTGCAGAAAGGCTGGCGGTTGCCGGAGTACACAGTGACCCAGGAGTCTGGGCCAGCCCACCGCAAAGAATTCACCATGACCTGTCGAGTGGAGCGTTTCATTGAGATTGGGAGTGGCACTTCCAAAAAATTGGCAAAGCGGAATGCGGCGGCCAAAATGCTGCTTCGAGTGCACACGGTGCCTCTGGATGCCCGGGATGGCAATGAGGTGGAGCCTGATGATGACCACTTCTCCATTGGTGTGGGCTCCCGCCTGGATGGTCTTCGAAACCGGGGCCCAGGTTGCACCTGGGATTCTCTACGAAATTCAGTAGGAGAGAAGATCCTGTCCCTCCGC";
		//Homo sapiens HIV-1 Tat interacting protein, 60kDa (HTATIP),
		String s5 = "AGTGCCCAGCGAGACAGCCCCGGCCTCGGTTTTTCCCCAGAATGGAGCCGCCCGTAGGGCAGTGGCAGCCCAGCCAGGACGGAAGCGAAAATCGAATTGTTTGGGCACTGATGAGGACTCCCAGGACAGCTCTGATGGAATACCGTCAGCACCACGCATGACTGGCAGCCTGGTGTCTGATCGAAGCCACGACGACATCGTCACCCGGATGAAGAACATTGAGTGCATTGAGCTGGGCCGGCACCGCCTCAAGCCGTGGTACTTCTCCCCGTACCCACAGGAACTCACCACATTGCCTGTCCTCTACCTGTGCGAGTTCTGCCTCAAGTACGGCCGTAGTCTCAAGTGTCTTCAGCGTCATTTGACCAAGTGTGACCTACGACATCCTCCAGGCAATGAGATTTACCGCAAGGGCACCATCTCCTTCTTTGAGATTGATGGACGTAAGAACAAGAGTTATTCCCAGAACCTGTGTCTTTTGGCCAAGTGTTTCCTTGACCATAAGACACTGTACTATGACACAGACCCTTTCCTCTTCTACGTCATGACAGAGTATGACTGTAAGGGCTTCCACATCGTGGGCTACTTCTCCAAGGAGAAAGAATCAACGGAAGACTACAATGTGGCC";
		// Homo sapiens HIV-EP2/Schnurri-2 gene, complete cds. 
		String s6 = "GAAGTGTCATGTACACAAGCATTTCTCAGATACTTGGGCAGAATAGCCCTGCCATTGTCATATGCAAAGTCGATGAGAATATGACCCAAAGGACACTGGTCACCAACGCAGCCATGCAAGGGATAGGATTCAACATTGCCCAGGTGCTGGGGCAGCATGCGGGCTTGGAGAAGTACCCCATTTGGAAAGCACCTCAGACTTTGCCCCTCGGCTTAGAATCCTCCATCCCCTTGTGTTTACCTTCCACCTCTGACAGCGTGGCCACCCTGGGAGGTAGCAAGCGAATGCTTTCTCCAGCCAGTAGCTTGGAGCTCTTCATGGAAACCAAGCAGCAGAAAAGGGTCAAAGAAGAAAAGATGTACGGACAGATTGTGGAGGAGCTTAGTGCTGTGGAGCTGACCAACTCAGACATCAAAAAGGACCTCTCCCGCCCCCAGAAACCCCAGCTGGTTCGACAAGGATGTGCTTCTGAGCCAAAAGATGGCTTGCAGTCAGGGTCATCTTCCTTCTCCTCGCTGTCGCCCTCCTCATCTCAAGACTATCCTTCTGTTAGCCCGTCTTCCAGGGAGCCATTCCCGCCCAGCAAGGAGATGCTTTCCGGTTCCCGGGCACCACTTCCGGGGCAGAAGTCCAGTGGGCCTTC";		
		
		String[] inputSequences = {s1, s2, s3, s4, s5, s6};
		
		return inputSequences;
	}
	
	public Alignment getDNAHIVClustalWSolution()
	{						                                
		Alignment solution = new Alignment();
		solution.addSequence(new Sequence("GAAGGAAATCAGATACATGTTATAAAGCCAGTTTTACCAAAGCTAAACAATCTGTTTGAATATGCGGTGTCAGAGGAAAATGGATGTTGGCTCTTTCACCCATCCTGGCATATGTGTATTTATAAAAGAATGTTTGAAAGTGAAA-ACAAAATCCTGTCCAAAGAAGGTG-TTATCCATTT-TTTGGAGCTGTATGAAACAAAGATTCTTCCATTTTCAC-CAGAATTTTCTGAGTTTATTATTGGACCATTAATGGATGCGCT--TTCAGAG--AGCTCTCTGTATAGCA-GGT--CCCCAGGCCAGCCAATAG--GAAGCTGTTCTCCATTGGGACTGAAATT-ACA--GAAGTTTTTAGTCACTTATATTTCTC--TTCTT-CCAG-AAGAAATAAAGAGTAGCTTCC---TATTGAAGTTTATTCGGAAGATGACAAGTAGGC-ATTGGTGT-GCTGTT-CCCATTTTGTTTCT-ATCTAAGGCTTTGGCAAATGTCCCAAGACATAAGGCCCTGGGTATAGATGGGCTTCTTGCTCTCAGGGATGTTATTCATTGCACTATGATCACACATCAGATTCTCCTGAGAGGGGCAGCCCAATGCTACCTTCTTCAAACAGCTATGAATTTGCTAGATGTGGAGAAAGTGTCACTTTCT"));
		solution.addSequence(new Sequence("GAAGGAAATCAGATACATGTTATAAAGCCAGTTTTACCAAAGCTAAACAATCTGTTTGAATATGCGGTGTCAGAGGAAAATGGATGTTGGCTCTTTCACCCATCCTGGCATATGTGTATTTATAAAAGAATGTTTGAAAGTGAAA-ACAAAATCCTGTCCAAAGAAGGTG-TTATCCATTT-TTTGGAGCTGTATGAAACAAAGATTCTTCCATTTTCAC-CAGAATTTTCTGAGTTTATTATTGGACCATTAATGGATGCGCT--TTCAGAG--AGCTCTCTGTATAGCA-GGT--CCCCAGGCCAGCCAATAG--GAAGCTGTTCTCCATTGGGACTGAAATT-ACA--GAAGTTTTTAGTCACTTATATTTCTC--TTCTT-CCAG-AAGAAATAAAGAGTAGCTTCC---TATTGAAGTTTATTCGGAAGATGACAAGTAGGC-ATTGGTGT-GCTGTT-CCCATTTTGTTTCT-ATCTAAGGCTTTGGCAAATGTCCCAAGACATAAGGCCCTGGGTATAGATGGGCTTCTTGCTCTCAGGGATGTTATTCATTGCACTATGATCACACATCAGATTCTCCTGAGAGGGGCAGCCCAATGCTACCTTCTTCAAACAGCTATGAATTTGCTAGATGTGGAGAAAGTGTCACTTTCT"));
		solution.addSequence(new Sequence("GACAGTCTAGTGGTTCGAGTAATTTTGGAGGTTTCCCCACAGCAAGTCACTCTC-----CTTTTCAGCCCCAAACTACAGGTGGAAGTGCTGCAT-CAGTAA---ATGCTAATT-----TTGCTCA----TTTTGATAACTTCCCCAAATCCTCCAGTGCTGATTTTGGAACCTTCAATACTTCCCAGAGTCATCAAACAGCATCAGCTGTTAG-TAAAGTTTCAACGAACAAAGCTGGTTTACAGACTGCAGACAAATATGCAGCACTTGCT--AATT---TAGACAATA-TCT--TCAGTGCCGGGCAAGGTG--GTGATCAGGGA--AGTGGCTTTGGGACC-ACAGGTAAAGCTCCTGTTGGTTCTGTGGTTT--CAGTT-CCCA-GT-CAGTCAAGTGCATCTTCA---GACAAGTATGCAGCTCTGGCAGAACTAGACAGC-GTTTTCAGTTCTGCAGCCACCTCCAGTAAT-GCGTATACTTCCAC-AAGTAATGCTAGCAGCAATGTTTTTGGAACAGTGCCAGTGGTTGCTTCTGCACA-GACACAGCCTGCTTCATCAA-GTGTGCCTGCTCCATTTGG-AGCTACGCCTTCCACAAATCCATTTGTTGCTGCTGCTGGTCCTTCTGTGGCATCTTCTACA--AACCCAT"));
		solution.addSequence(new Sequence("GCGACACCAGCTGCACTGGTCAGGGCCCCAGCAAGAAGGCAGCCAAGCACAAGGCAGCTGAGGTGGCCCTCAAACACCTCAAAG-GGGGGAGCATGCTGGAGCCGGCCCTGGAG-----GACAGCAGTTCTTTTTCTCCCCTAGACTCTTCACTGCCTGAGGACATTCCGGTTTTTACTGCTGCAGCAGCTGC-TACCCCAGTTCCATCTGTAGTCCTAACCAGGAGCCCCCCCATGGAACTGCAGCCCCCTGTCTCCCCTCAGCAGTCTGAG--TGCAACCCCGTTGGTGCTCT--GCAGGAGCTGGTGGTGCAGAAAGGCTGGCGGTTGCCGGAGTACACAGTGACCCAGGAGTCTGGGCCAGCCCACCGCAAAG--AATTC-ACCATGACCTGTCGAGTGGAGCGTTT---CATTGAGA-TTGGGAGTGGCACTTCCAAAAAATTGGCAAAGCGGAATGCGGCGGCCAAAATGCT-GCTTCGAG-TGCACACGGTGCCTCTGGATGCCCGGGATGGCAATGAGGTGGA--GCCTGATGATGACCA-CTTCTCCATTGGTGTGGGCTCCCG-CCTGGATGGTCTTCGAAACCGGGGCCCA-GGTTGCACCTGGGATTCTCTACGAAATTCAGTAGGAGAGAAGATCCTGTCCCTCCGC"));
		solution.addSequence(new Sequence("AGTGCCCAGCGAGACAGCCCCGGCCTCGGTTTTTCCCCAGAATGGAGCCGCCCG-----TAGGGCAGTGGCAGCCCAGCCAGGACGGAAGCGAAA--ATCGAATTGTTTGGGCA-----CTGATGAGGACTCCCAGGACAGCTCTGATGGAATACCGTCAGCACCACGCA-TGACTGGCAGCCTGGTGTCTGATCGAAGCCACGACGACATCGTCACCCGGATGAAGAACATTGAGTGCATTGAGCTGGGCCGGCACCGCCTCAAGCCGTGGT--ACTTCTCCCCGTA----CCC--ACAGGAACTCACCACATTGCCTGTCCTCTACCTGTGCGAGTTCTGCCTCAAGTACGGCCGTAGTCTCAAGTGTCTTCAGCGTCATTTGACCAAGTGTGACCTACGACATCCTCCAGGCAATGAGATTTACCGCAAGGGCACCATCTCCTTCTTTGAGATTGATGGACGTAAGAACAAGAGTTATTCCCAG---AACCTGTGTCTTTTGGCCAAGTGTTTCCTTGACCATAAGACACTG-TACTATGACACAGACCCTTTCCTCTTCTACGTCATGACAGAGTATGACTGTAAGGGCTTCCACATCGTGGGCTACTTCTCCAAGGAGAAAGAATCAACGGAAGACTACAATGTGG-------CC"));
		solution.addSequence(new Sequence("GAAGTGTCATGTACACAAGCATTTCTCAGATACTTGGGCAGAATAGCCCTGCCATTGTCATATGCAAAGTCGATGAGAATATGACCCAAAGGACACTGGTCACCAACGCAGCCATGCAAGGGATAGGATTCAACATTGCCCAGGTGCTGGGGCAGCATGCGGGCTTGGAGAAGTACCCCATTTGGAAAGCACCTCAGACTTTGCCCCTCGGCTTAGAATCCTCCATCCCCTTGTGTTTACCTTCCACCTCTGACAGCGTGGCCACCCTGGGAGGTAGCAAGCGAATGCTTTCTCCAGCCAGTAGCTTGGAGCTCTTCATGGAAACCAAGCAGCAGAAAAGGGTCAAAGAAGAAAAGATGTACGGACAGATTGTGGAGG-AGCTTAGTGCTGTGGAGCTGACCAA----CTCAGACATCAAAAAGGACCTCTCCCGCCCCCAGAAACC---CCAGCTGGTTCGACAAGGATGTGCTTCTGAGCCAAAAGATGGCTTGCAGTCAGGGTCATCTTCCTTCTCCTCGCTGTCGCCCTCCTCATCTCAAGACTATCCTTCTGTTAGCCCGTCTTCCAGGGAGCCATTCCCGCCCAG---------CAAGGAGATGCTTTCCGGTTCCCGGGCACCACTTCCGGGGCAGAAGTCCAGTGGGCCTTC"));		
		return solution;
	}
	
	public String[] getDNABRCA1Sequences()
	{	
		// GBREFSEQNEW:31560811 	Mus musculus breast cancer 1 (Brca1), mRNA.
		String s1 = "CAGAGTATTTCTATTTCAAATGTGTGTGTGGAGCCATGTGGCACAGATGCTCATGCCAGCTCATTACAGCCTGAGACCAGCAGTTTATTGCTCATTGAAGACAGAATGAATGCAGAAAAGGCTGAATTCTGTAATAAAAGCAAACAGCCTGGCATAGCAGTGAGCCAGCAGAGCAGATGGGCTGCAAGTAAAGGAACATGTAACGACAGGCAGGTTCCCAGCACTGGGGAAAAGGTAGGTCCAAACGCTGACTCCCTTAGTGATAGAGAGAAGTGGACTCACCCGCAAAGTCTGTGCCCTGAGAATTCTGGAGCTACCACCGATGTTCCTTGGATAACACTAAATAGCAGCGTTCAGAAAGTTAATGAGTGGTTTTCCAGAACTGGTGAAATGTTAACTTCTGACAGCGCATCTGCCAGGAGGCACGAGTCAAATGCTGAAGCAGCTGTTGTGTTGGAAGTTTCAAACGAAGTGGATGGGGGTTTTAGTTCTTCAAGGAAAACAGACTTAGTAACCCCCGACCCCCATCATACTTTAATGTGTAAAAGTGGAAGAGACTTCTCCAAACCAGTAGAGGATAATATCAGTGATAAAATATTTGGGAAATCCTATCAGAGAAAGGGAAGCCGCCCTCACCTGAACCATGTGACTGAAATTATAGGCACATTTATTACAGAACCACAGATAACACAAGAG";
		// GBREFMAM:6978572 	Rattus norvegicus breast cancer 1 (Brca1), mRNA.
		String s2 = "CCGCGTATTTCTGTTGCAAACGTGCACGTGGAGCCGTGTGGCACAGATGCTCGTGCCAGCTCATTACAGCGTGGGACCCGCAGTTTATTGTTCACTGAGGACAGACTGGATGCAGAAAAGGCTGAATTCTGTGATAGAAGCAAACAGTCTGGCGCAGCAGTGAGCCAGCAGAGCAGATGGGCTGACAGTAAAGAAACATGTAATGGCAGGCCGGTTCCCCGCACTGAGGGAAAGGCAGATCCAAATGTGGATTCCCTCTGTGGTAGAAAGCAGTGGAATCATCCGAAAAGCCTGTGCCCTGAGAATTCTGGAGCTACCACTGACGTTCCTTGGATAACACTGAATAGCAGCATTCAGAAAGTGAATGAGTGGTTTTCCAGAACTGGTGAAATGTTAACTTCTGACAATGCATCTGACAGGAGGCCTGCGTCAAATGCAGAAGCTGCTGTTGTGTTAGAAGTTTCAAATGAAGTGGATGGATGTTTCAGTTCTTCAAAGAAAATAGACTTAGTTGCCCCTGATCCCGATAATGCTGTAATGTGTACAAGTGGAAGAGACTTCTCCAAGCCAGTAGAGAATATTATCAACGATAAAATATTTGGGAAAACCTATCAGAGAAAGGGAAGCCGCCCTCACTTGAACCATGTGACTGAAATTATAGGCACATTTACTACAGAACCACAGATTATACAAGAG";
		// GBREFMAM:61740516 	Canis familiaris breast cancer 1, early onset (BRCA1), mRNA.
		String s3 = "CAGGGTATTTCTGTTTCAAACTTGCATGTGGAGCCATGTGGCACAAATACTCATGCCAGCTCATTACAGCATGAGAACAGCAGTTTATTACTCACTAAACACAGAATGAATGTAGAAAAGGCTGAAATCTGTAATAACAGCAAACAGCCTGGCTTAGCAAGGAGCCAACAGAGCAGATGGGCTGAAAGTAAGGAAACATGTAATGATAGGCAGATTCCCAGCACAGAGAAAAAGGTAGTTGTGAATGCTGATCTCCTGTGTGGGAGAAAAGAACTGAATAAACAGAAACCTCCACACTCTGATAGTCCTAGAGATTCCCAAGATGTTCCTTGGATAACACTGAATAGTAGCATACGGAAAGTTAATGAGTGGTTTTCCAGAAGTGACGAAATATTAACTTCTGATGATTCACATGACAGAGGATCTGAATTGAATACTGAAGTAGGTGGTGCAGTAGAAGTTCCAAATGAAGTGGGTGAATATTCTGGTTCTTCTGAGAAAATAGACTTAATGGCCAGTGATCCTCAGGATGCTTTCATATGTGAAAGTGAAAGAGTCCACACCAAGCCAGTAGGAGGTAATATCGAAGATAAAATATTTGGAAAAACCTATCGGAGGAAGGCAAGCCTCCCTAAGGTGAGCCACACAACTGAAGTTCTAACTATAGGAGCGTGTGCTATAGAACCTCAGACAATGCAAACC";
		//GBMAM:6694628 		Hipposideros commersoni Brca1 (Brca1) gene, partial cds.
		String s4 = "TTTTCAACTTGCATGTGGAGCCATGTGGCACAAATACTCATGCCAGCTCTTTACATTATGAGCACAGCAGTTTATTACTCACTGAAGACAGAATGAATGTAGAAAAGGCTGAATTCTGTAATAAAAGCAAGCAGCCTGGCTTAGCAAGGAGCCAACAGAGCAGATGGGCTGAAAGTAAGGAAACATGTAATGATAGGCAGACTCCCAGCACAGAGGAAAATGTAGTTCTGAATACTGATCCCCTGAATGGGAGAAAAGAACTGAATAAGCAGAAACCTCCATGCTCTGACAGTCCTAGGGATTCCCAAGTTGTTGCATGGATAACACAGAATAGTAGCATACAGAAAGTTAATGAGTGGTTTTCCAGACGTGATGAAATATTAACTTCTCATAGCTCATGTTATGGGAGAGCTGAATCAAATACAGAAGTATCTGGTGCAGTAGAAGTTCCACTTGAAGTAGATGGATTTTCTGGCTCTACAGAGAAAATAACCTTAATGACCAGTGATCCTCATGATGCTGTAATATGTGAAAGTGGAAGAGTCCACTCCAAACCATTGGAAAGTACTATTGAAGATAAAATATTTGGGAAAACCTATCGGAGGAAGGCAAGCCTCCCTAACTTCAGCCACACAACTGAAAACATAATTATAGGAGCATCTGCTGTAGAACCTCAGATAACACAAGAG";
		//GBREFMAM:113865840 	Pan troglodytes breast cancer 1, early onset (BRCA1), mRNA.
		String s5 = "CAGGGTAGTTCTGTTTCAAACTTGCATGTGGAGCCATGTGGCACAAATACTCATGCCAGCTCATTACAGCATGAGAACAGCAGTTTATTACTCACTAAAGACAGAATGAATGTAGAAAAGGCTGAATTCTGTAATAAAAGCGAACAGCCTGGCTTAGCAAGGAGCCAACATAACAGATGGGCTGGAAGTAAGGAAACATGTAATGATAGGCGGACTCCCAGCACAGAAAAAAAGGTAGATCTGAATGCTGATCCCCTGTGTGAGAGAAAAGAATGGAATAAGCAGAAACTGCCATGCTCAGAGAATCCTAGAGATACTGAAGATGTTCCTTGGATAACACTAAATAGCAGCATTCAGAAAGTTAATGAGTGGTTTTCCAGAAGTGATGAACTGTTAGGTTCTGATGACTCACATGATGGGGGGTCTGAATCAAATGCCAAAGTAGCTGATGTATTGGACGTTCTAAATGAGGTAGATGAATATTCTGGTTCTTCAAAGAAAATAGACTTACTGGCCAGCGATCCTCATGAGGCTTTAATATGTAAAAGTGAAAGAGTTCACTCCAAATCAGTAGAGAGTAATACTGAAGACAAAATATTTGGGAAAACCTATCGGAGGAAGGCAAGCCTCCCCAACTTAAGCCATGTAACTGAAAATCTAATTATAGGAGCATTTGTTACTGAGCCACAGATAATACAAGAG";
		// GBREFMAM:30466259 	Bos taurus breast cancer 1, early onset (BRCA1), mRNA.
		String s6 = "CAGGGTATTTCTGTTTCAGACTTTCACGTGGAGCCATGTGGCACAGATACTCATGCCAGCTCATTACAGCATGAGAACAGCAGTTTATTGCTCACTGAAAACAGACTGAATGTAGAAAAGGCTGAATTCTGTAATAAAAGCAAACAGCCTGTCTTAGTAAAGAGCCAGCAGAGCAGATGGGCTGAAAGTAAGGGCACATGTAAGGATAGGCAGATTCCCAGCACTGAGAAAAAGATAGTTCTGAATACTGATCCCCTGTACAGAAGAAAAGAACTGCGTAAGCAGAAACCTGCATGCCCTGACAGTCCTGGAGATTCCCAAGATGTTCCTTGGGTAACCCTGAATAATAGCATACAGAAAGTTAATGACTGGTTTTCCAGAAGTGATGAAATATTAACTTCTGATGACTCGTGCGATGGGGGGTCTGAATCAAATAATGAAGTAGCTGGTGCAGTGGAAATTCCAAATAAAGTAGATGGATATTCAGGTTCTTCAGAGAAAATCAACTTAATGGCCAGTGATCCTCATGGTACTTTAATACACGAAAGAGTCCACTCCAAACCCGTAGAGAGTAATATTGAAGATAAAATATTTGGGAAAACCTATCGGAGGAAGTCAAGTCTCCCTAACTTCAGCCACATAGCTGAAGATCTAATTCTAGGCGCATTTACTGTAGAACCTCAGATAACACAAGAG";		
		// GBREFMAM:77020290 	Monodelphis domestica breast cancer 1, early onset (BRCA1), mRNA.
		String s7 = "CGGGGTGTTTCTTCCTCAGACTTGAATATGAAGCCATGGAACACAGACATTCATGCTAGCTCATTACCACCTGAGATCACCAGTGTATTGACTAACACAGTCAGCATGAACATAGAAAAGGCTGAACTCTGTGATAAAAGTAAAAGGCCTGGTTTAGCAAGGAGCCAGCAGATAAGTCAGGATAATAGTAAGGAAAAATGTAGTGCTGGGAAGACCTCATATGCAGAGGTGCCGCATGAGCTGAACCCCCATCATCTGTATGAGAGGCAAGAACTAGAGGAACAGCCAGAGTGCCCCAAGTACCCCAGAGGAAATCCTCAAAACTGCTTGTCTGGAACCAAACTGAAAAGCAGTATTCAGAAAGTTAATGACTGGTTATCCAGAAGTAATGACATTTTAGTCTCTGATTATTCCTCTGTTAGGATCCATGAACAGAATGCAGAGATGGCTAGTGTCTTAGAAATTGGGCATCCAGATACCACAGATGGAAATTCTAGCATTTCTGGGAAGACTGACTTGGTGGCTGACTCCACTGATGGTGCCTGGCTACATATGTCTGAAAGAAGCTGCCCCAGGCAGGCAGAGAACAACAATATTGAAGACAAAATATTTGGAAAAACCTACCATAGAAAGTCAGTTCACACTAATTTGAATTACGTAACTGAAAACTTGATTGTTGGAGCTGTTGCTTCTGATTGTTTGATCCCTCCAGAG";
		//GBMAM:28199992 		Didelphis virginiana BRCA1 (BRCA1) gene, partial cds.
		String s8 = "GTGGAGCCATGTGGCACAGATGCTCGTGCCAGCTCATTACTGCCTGACATCACCAGTGTATTGCCTAACACAGACAGCATGAATGTAGAAAAGGCTGAACTCTGTGATAAAAGCAAAAGGCCTGATTTAGCATGGAGCCAGCAGATCAGTCAGGATGAAAGTAAGGAAAAATGTATTGCTGGGAAGACCTCAGATGCAAAGGAGTTACATGAGCTAAATGCCCATCATCTGTATGAGAGGCAAGAACTAGAAGAGCAGCCAGAGTGCCCCAACTACCCCAGAGGAAATTCTCAAAACTGCTTGTCTGGAACCAAACTGAAAAGTATTCAGAAAGTTAATGACTGGTTATCCAAAAGTAATGACATTTTAGTCTCTGATTACTCCTCTGGTAGGATCCATGAACAGAATGCAGAGATGGATAGTGTCTTAGAAGATGGGCATCCAGATGTTACAGATGGAAATTCTAGCATTTCTGGGAAGACTGACTTGGTGGCTGACTCCACCGATGGTGCCTGGCTACATATGTCTGAAAGAAGCTGCTCCAGGAAGGCAGAGAGCAACAATATTGAAGACAAAATCTTCGGCAAGACCTACCATAGAAAATCAGTTCACATTAATTTGAATTATGTGACTGAAAACTTGATTGTTGGAGCTGTTGATTCTGATTCTTTGATCCCTCCAGAG";
		// GBMAM:28199994 		Macropus rufus BRCA1 (BRCA1) gene, partial cds.
		String s9 = "TGTGGCACAGATGCTCGTGCCACCTCATTACTTCCTGAAACCACCAGCTTATCGCCCAACACAGACCGAATGAATGTAGAAAAGGCTGAACTCTGTAATAAAAGCAAACAGCCTGGCTTAGCAAAAAACCAACAGAGCAGTCTGGATGAAAGTAAGGAAATATGTAGTGCTGGAAAGACCCTGGGTGCCCATGAGCTGAATGCCCATCATCCATGCGAGAGGAAAGAACTAGAGGATGAGCCACAGCACCCTGAGAGCCCCAGAGGTAATCCTCAGAACTGCCAGTCTGGAACCAAACTGAAAAGTAGTATTCAGAAAGTTAATGAGTGGTTATCCAGGAGTAATGATATTTTAACTTCTGATAACTCCTATAGTAGGAACCATGAGCAGAATGCAGAGATGCCTAGTGCCTTAAAAGATGGGTATCCAGATACTGCAGATGCAAATTCTAACATTTCTGAGAAGACTGACCCAGTGGCTGACATCACTTATGATCCCTGGCCACATGTGCCTGAAAGAAGCTGCCCCAGGCCAGCAGAAAACAATAACATTGAAGATAAAATATTTGGAAAAACCTATCGGAGAAAATCAGGTCACCCTCATTTGAATTGTATAACTGAAAACTTGTTTGCTGGAGCTGTTGTTGCTCCTGATTCTTTGATCCCTCCAGAG";		
		
		String[] inputSequences = {s1, s2, s3, s4, s5, s6, s7, s8, s9};
		
		return inputSequences;
	}
	
	public Alignment getDNABRCA1ClustalWSolution()
	{						                                
		Alignment solution = new Alignment();
		solution.addSequence(new Sequence("CAGAGTATTTCTATTTCAAATGTGTGTGTGGAGCCATGTGGCACAGATGCTCATGCCAGCTCATTACAGCCTGAGACCAGCAGTTTATTGCTCATTGAAGACAGAATGAATGCAGAAAAGGCTGAATTCTGTAATAAAAGCAAACAGCCTGGCATAGCAGTGAGCCAGCAGAGCAGATGGGCTGCAAGTAAAGGAACATGTAACGACAGGCAGGTTCCCAGCACTGGGGAAAAGGTAGGTCCAAACGCTGACTCCCTTAGTGATAGAGAGAAGTGGACTCACCCGCAAAGTCTGTGCCCTGAGAATTCTGGAGCTA----CCACCGATGTT--CCTTGGATAACACTAAATAGCAGCGTTCAGAAAGTTAATGAGTGGTTTTCCAGAACTGGTGAAATGTTAACTTCTGACAGCGCATCTGCCAGGAGGCACGAGTCAAATGCTGAAGCAGCTGTTGTGTTGGAAGTT------TCAAACGAAGTGGATGGGGGTTTTAGTTCTTCAAGGAAAACAGACTTAGTAACCCCCGACCCCCATCATACTTTAATGTGTAAAAGTGGAAGAGACTTCTCCAAACCAGTAGAGG---ATAATATCAGTGATAAAATATTTGGGAAATCCTATCAGAGAAAGGGAAGCCGCCCTCACCTGAACCATGTGACTGAA------ATTATAGGCACATTTA---TTACAGAACCACAGATAACACAAGAG"));
		solution.addSequence(new Sequence("CCGCGTATTTCTGTTGCAAACGTGCACGTGGAGCCGTGTGGCACAGATGCTCGTGCCAGCTCATTACAGCGTGGGACCCGCAGTTTATTGTTCACTGAGGACAGACTGGATGCAGAAAAGGCTGAATTCTGTGATAGAAGCAAACAGTCTGGCGCAGCAGTGAGCCAGCAGAGCAGATGGGCTGACAGTAAAGAAACATGTAATGGCAGGCCGGTTCCCCGCACTGAGGGAAAGGCAGATCCAAATGTGGATTCCCTCTGTGGTAGAAAGCAGTGGAATCATCCGAAAAGCCTGTGCCCTGAGAATTCTGGAGCTA----CCACTGACGTT--CCTTGGATAACACTGAATAGCAGCATTCAGAAAGTGAATGAGTGGTTTTCCAGAACTGGTGAAATGTTAACTTCTGACAATGCATCTGACAGGAGGCCTGCGTCAAATGCAGAAGCTGCTGTTGTGTTAGAAGTT------TCAAATGAAGTGGATGGATGTTTCAGTTCTTCAAAGAAAATAGACTTAGTTGCCCCTGATCCCGATAATGCTGTAATGTGTACAAGTGGAAGAGACTTCTCCAAGCCAGTAGAGA---ATATTATCAACGATAAAATATTTGGGAAAACCTATCAGAGAAAGGGAAGCCGCCCTCACTTGAACCATGTGACTGAA------ATTATAGGCACATTTA---CTACAGAACCACAGATTATACAAGAG"));
		solution.addSequence(new Sequence("CAGGGTATTTCTGTTTCAAACTTGCATGTGGAGCCATGTGGCACAAATACTCATGCCAGCTCATTACAGCATGAGAACAGCAGTTTATTACTCACTAAACACAGAATGAATGTAGAAAAGGCTGAAATCTGTAATAACAGCAAACAGCCTGGCTTAGCAAGGAGCCAACAGAGCAGATGGGCTGAAAGTAAGGAAACATGTAATGATAGGCAGATTCCCAGCACAGAGAAAAAGGTAGTTGTGAATGCTGATCTCCTGTGTGGGAGAAAAGAACTGAATAAACAGAAACCTCCACACTCTGATAGTCCTAGAGATT----CCCAAGATGTT--CCTTGGATAACACTGAATAGTAGCATACGGAAAGTTAATGAGTGGTTTTCCAGAAGTGACGAAATATTAACTTCTGATGATTCACATGACAGAGGATCTGAATTGAATACTGAAGTAGGTGGTGCAGTAGAAGTT------CCAAATGAAGTGGGTGAATATTCTGGTTCTTCTGAGAAAATAGACTTAATGGCCAGTGATCCTCAGGATGCTTTCATATGTGAAAGTGAAAGAGTCCACACCAAGCCAGTAGGAG---GTAATATCGAAGATAAAATATTTGGAAAAACCTATCGGAGGAAGGCAAGCCTCCCTAAGGTGAGCCACACAACTGAAGTTCTAACTATAGGAGCGTGTG---CTATAGAACCTCAGACAATGCAAACC"));
		solution.addSequence(new Sequence("-------------TTTTCAACTTGCATGTGGAGCCATGTGGCACAAATACTCATGCCAGCTCTTTACATTATGAGCACAGCAGTTTATTACTCACTGAAGACAGAATGAATGTAGAAAAGGCTGAATTCTGTAATAAAAGCAAGCAGCCTGGCTTAGCAAGGAGCCAACAGAGCAGATGGGCTGAAAGTAAGGAAACATGTAATGATAGGCAGACTCCCAGCACAGAGGAAAATGTAGTTCTGAATACTGATCCCCTGAATGGGAGAAAAGAACTGAATAAGCAGAAACCTCCATGCTCTGACAGTCCTAGGGATT----CCCAAGTTGTT--GCATGGATAACACAGAATAGTAGCATACAGAAAGTTAATGAGTGGTTTTCCAGACGTGATGAAATATTAACTTCTCATAGCTCATGTTATGGGAGAGCTGAATCAAATACAGAAGTATCTGGTGCAGTAGAAGTT------CCACTTGAAGTAGATGGATTTTCTGGCTCTACAGAGAAAATAACCTTAATGACCAGTGATCCTCATGATGCTGTAATATGTGAAAGTGGAAGAGTCCACTCCAAACCATTGGAAA---GTACTATTGAAGATAAAATATTTGGGAAAACCTATCGGAGGAAGGCAAGCCTCCCTAACTTCAGCCACACAACTGAAAACATAATTATAGGAGCATCTG---CTGTAGAACCTCAGATAACACAAGAG"));
		solution.addSequence(new Sequence("CAGGGTAGTTCTGTTTCAAACTTGCATGTGGAGCCATGTGGCACAAATACTCATGCCAGCTCATTACAGCATGAGAACAGCAGTTTATTACTCACTAAAGACAGAATGAATGTAGAAAAGGCTGAATTCTGTAATAAAAGCGAACAGCCTGGCTTAGCAAGGAGCCAACATAACAGATGGGCTGGAAGTAAGGAAACATGTAATGATAGGCGGACTCCCAGCACAGAAAAAAAGGTAGATCTGAATGCTGATCCCCTGTGTGAGAGAAAAGAATGGAATAAGCAGAAACTGCCATGCTCAGAGAATCCTAGAGATA----CTGAAGATGTT--CCTTGGATAACACTAAATAGCAGCATTCAGAAAGTTAATGAGTGGTTTTCCAGAAGTGATGAACTGTTAGGTTCTGATGACTCACATGATGGGGGGTCTGAATCAAATGCCAAAGTAGCTGATGTATTGGACGTT------CTAAATGAGGTAGATGAATATTCTGGTTCTTCAAAGAAAATAGACTTACTGGCCAGCGATCCTCATGAGGCTTTAATATGTAAAAGTGAAAGAGTTCACTCCAAATCAGTAGAGA---GTAATACTGAAGACAAAATATTTGGGAAAACCTATCGGAGGAAGGCAAGCCTCCCCAACTTAAGCCATGTAACTGAAAATCTAATTATAGGAGCATTTG---TTACTGAGCCACAGATAATACAAGAG"));
		solution.addSequence(new Sequence("CAGGGTATTTCTGTTTCAGACTTTCACGTGGAGCCATGTGGCACAGATACTCATGCCAGCTCATTACAGCATGAGAACAGCAGTTTATTGCTCACTGAAAACAGACTGAATGTAGAAAAGGCTGAATTCTGTAATAAAAGCAAACAGCCTGTCTTAGTAAAGAGCCAGCAGAGCAGATGGGCTGAAAGTAAGGGCACATGTAAGGATAGGCAGATTCCCAGCACTGAGAAAAAGATAGTTCTGAATACTGATCCCCTGTACAGAAGAAAAGAACTGCGTAAGCAGAAACCTGCATGCCCTGACAGTCCTGGAGATT----CCCAAGATGTT--CCTTGGGTAACCCTGAATAATAGCATACAGAAAGTTAATGACTGGTTTTCCAGAAGTGATGAAATATTAACTTCTGATGACTCGTGCGATGGGGGGTCTGAATCAAATAATGAAGTAGCTGGTGCAGTGGAAATT------CCAAATAAAGTAGATGGATATTCAGGTTCTTCAGAGAAAATCAACTTAATGGCCAGTGATCCTCATGGTACTTTAATACACGAA------AGAGTCCACTCCAAACCCGTAGAGA---GTAATATTGAAGATAAAATATTTGGGAAAACCTATCGGAGGAAGTCAAGTCTCCCTAACTTCAGCCACATAGCTGAAGATCTAATTCTAGGCGCATTTA---CTGTAGAACCTCAGATAACACAAGAG"));		
		solution.addSequence(new Sequence("CGGGGTGTTTCTTCCTCAGACTTGAATATGAAGCCATGGAACACAGACATTCATGCTAGCTCATTACCACCTGAGATCACCAGTGTATTGACTAACACAGTCAGCATGAACATAGAAAAGGCTGAACTCTGTGATAAAAGTAAAAGGCCTGGTTTAGCAAGGAGCCAGCAGATAAGTCAGGATAATAGTAAGGAAAAATGTAGTGCTGGGAAGACCTCATATGCAGAGGTGCCGCATGAGCTGAACCCCCATCATCTGTATGAGAGGCAAGAACTAGAGGAACAGCCAGA---GTGCCCCAAGTACCCCAGAGGAAATCCTCAAAACTGCTTGTCTGGAACCAAACTGAAAAGCAGTATTCAGAAAGTTAATGACTGGTTATCCAGAAGTAATGACATTTTAGTCTCTGATTATTCCTCTGTTAGGATCCATGAACAGAATGCAGAGATGGCTAGTGTCTTAGAAATTGGGCATCCAGATACCACAGATGGAAATTCTAGCATTTCTGGGAAGACTGACTTGGTGGCTGACTCCACTGATGGTGCCTGGCTACATATGTCTGAAAGAAGCTGCCCCAGGCAGGCAGAGAACAACAATATTGAAGACAAAATATTTGGAAAAACCTACCATAGAAAGTCAGTTCACACTAATTTGAATTACGTAACTGAAAACTTGATTGTTGGAGCTGTTG---CTTCTGATTGTTTGATCCCTCCAGAG"));
		solution.addSequence(new Sequence("---------------------------GTGGAGCCATGTGGCACAGATGCTCGTGCCAGCTCATTACTGCCTGACATCACCAGTGTATTGCCTAACACAGACAGCATGAATGTAGAAAAGGCTGAACTCTGTGATAAAAGCAAAAGGCCTGATTTAGCATGGAGCCAGCAGATCAGTCAGGATGAAAGTAAGGAAAAATGTATTGCTGGGAAGACCTCAGATGCAAAGGAGTTACATGAGCTAAATGCCCATCATCTGTATGAGAGGCAAGAACTAGAAGAGCAGCCAGA---GTGCCCCAACTACCCCAGAGGAAATTCTCAAAACTGCTTGTCTGGAACCAAACTGAAA---AGTATTCAGAAAGTTAATGACTGGTTATCCAAAAGTAATGACATTTTAGTCTCTGATTACTCCTCTGGTAGGATCCATGAACAGAATGCAGAGATGGATAGTGTCTTAGAAGATGGGCATCCAGATGTTACAGATGGAAATTCTAGCATTTCTGGGAAGACTGACTTGGTGGCTGACTCCACCGATGGTGCCTGGCTACATATGTCTGAAAGAAGCTGCTCCAGGAAGGCAGAGAGCAACAATATTGAAGACAAAATCTTCGGCAAGACCTACCATAGAAAATCAGTTCACATTAATTTGAATTATGTGACTGAAAACTTGATTGTTGGAGCTGTTG---ATTCTGATTCTTTGATCCCTCCAGAG"));
		solution.addSequence(new Sequence("------------------------------------TGTGGCACAGATGCTCGTGCCACCTCATTACTTCCTGAAACCACCAGCTTATCGCCCAACACAGACCGAATGAATGTAGAAAAGGCTGAACTCTGTAATAAAAGCAAACAGCCTGGCTTAGCAAAAAACCAACAGAGCAGTCTGGATGAAAGTAAGGAAATATGTAGTGCTGGAAAGACCCTGGGTGCC---------CATGAGCTGAATGCCCATCATCCATGCGAGAGGAAAGAACTAGAGGATGAGCCACA---GCACCCTGAGAGCCCCAGAGGTAATCCTCAGAACTGCCAGTCTGGAACCAAACTGAAAAGTAGTATTCAGAAAGTTAATGAGTGGTTATCCAGGAGTAATGATATTTTAACTTCTGATAACTCCTATAGTAGGAACCATGAGCAGAATGCAGAGATGCCTAGTGCCTTAAAAGATGGGTATCCAGATACTGCAGATGCAAATTCTAACATTTCTGAGAAGACTGACCCAGTGGCTGACATCACTTATGATCCCTGGCCACATGTGCCTGAAAGAAGCTGCCCCAGGCCAGCAGAAAACAATAACATTGAAGATAAAATATTTGGAAAAACCTATCGGAGAAAATCAGGTCACCCTCATTTGAATTGTATAACTGAAAACTTGTTTGCTGGAGCTGTTGTTGCTCCTGATTCTTTGATCCCTCCAGAG"));
		return solution;
	}
	
	public String[] getAAHemoGlobinSequences()
	{		
		//Leghemoglobin_1_from_lupine
		String s1 = "GVLTDVQVALVKSSFEEFNANIPKNTHRFFTLVLEIAPGAKDLFSFLKGSSEVPQNNPDLQAHAGKVFKLTYEAAIQLQVNGAVASDATLKSLGSVHVSKGVVDAHFPVVKEAILKTIKEVVGDKWSEELNTAWTIAYDELAIIIKKEMKDAA";
		//Dwarf_sperm_whale_myoglobin
		String s2 = "VLSEGEWQLVLHVWAKVEADIAGHGQDILIRLFKHHPETLEKFDRFKHLKSEAEMKASEDLKKHGVTVLTALGAILKKKGHHEAELKPLAQSHATKHKIPIKYLEFISEAIIHVLHSRHPADFGADAQGAMSKALELFRKDIAAKYKELGYQG";
		//Sea_lamprey_hemoglobin
		String s3 = "PIVDTGSVAPLSAAEKTKIRSAWAPVYSNYETSGVDILVKFFTSTPAAQEFFPKFKGLTTADQLKKSADVRWHAERIINAVNDAVVSMDDTEKMSMKLRDLSGKHAKSFQVDPQYFKVLAAVIADTVAAGDAGFEKLMSMICILLRSAY";
		//Przewalski_Horse_hemoglobin
		String s4 = "VLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHFDLSHGSAQVKGHGKKVADALTNAVAHVDDMPNALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAAHLPAEFTPAVHASLDKFLASVSTVLTSKYR";
		//Human_hemoglobin_alpha_chain
		String s5 = "VLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHFDLSHGSAQVKGHGKKVADALTNAVAHVDDMPNALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAAHLPAEFTPAVHASLDKFLASVSTVLTSKYR";
		//Horse_hemoglobin_beta_chain
		String s6 = "VQLSGEEKAAVLALWDKVNEEEVGGEALGRLLVVYPWTQRFFDSFGDLSNPGAVMGNPKVKAHGKKVLHSFGEGVHHLDNLKGTFAALSELHCDKLHVDPENFRLLGNVLVVVLARHFGKDFTPELQASYQKVVAGVANALAHKYH";
		//Human_hemoglobin_beta_chain
		String s7 = "VHLTPEEKSAVTALWGKVNVDEVGGEALGRLLVVYPWTQRFFESFGDLSTPDAVMGNPKVKAHGKKVLGAFSDGLAHLDNLKGTFATLSELHCDKLHVDPENFRLLGNVLVCVLAHHFGKEFTPPVQAAYQKVVAGVANALAHKYH";
		String[] inputSequences = {s1, s2, s3, s4, s5, s6, s7};
		return inputSequences;
	}
	
	public Alignment getAAHemoGlobinClustalWSolution()
	{		
		Alignment solution = new Alignment();
		solution.addSequence(new Sequence("--------GVLTDVQVALVKSSFEEFNANIPKNTHRFFTLVLEIAPGAKDLFSFLKGSSEVP--QNNPDLQAHAGKVFKLTYEAAIQLQVNGAVASDATLKSLGSVHVSKGVVD-AHFPVVKEAILKTIKEVVGDKWSEELNTAWTIAYDELAIIIKKEMKDAA---"));
		solution.addSequence(new Sequence("---------VLSEGEWQLVLHVWAKVEADIAGHGQDILIRLFKHHPETLEKFDRFKHLKSEAEMKASEDLKKHGVTVLTALGAILKKKGH-----HEAELKPLAQSHATKHKIPIKYLEFISEAIIHVLHSRHPADFGADAQGAMSKALELFRKDIAAKYKELGYQG"));
		solution.addSequence(new Sequence("PIVDTGSVAPLSAAEKTKIRSAWAPVYSNYETSGVDILVKFFTSTPAAQEFFPKFKGLTTADQLKKSADVRWHAERIINAVNDAVVSMDDT--EKMSMKLRDLSGKHAKSFQVDPQYFKVLAAVIADTVAAG---------DAGFEKLMSMICILLRSAY-------"));
		solution.addSequence(new Sequence("---------VLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHF-DLS-----HGSAQVKGHGKKVADALTNAVAHVDD-----MPNALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAAHLPAEFTPAVHASLDKFLASVSTVLTSKYR------"));
		solution.addSequence(new Sequence("---------VLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHF-DLS-----HGSAQVKGHGKKVADALTNAVAHVDD-----MPNALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAAHLPAEFTPAVHASLDKFLASVSTVLTSKYR------"));
		solution.addSequence(new Sequence("--------VQLSGEEKAAVLALWDKV--NEEEVGGEALGRLLVVYPWTQRFFDSFGDLSNPGAVMGNPKVKAHGKKVLHSFGEGVHHLDN-----LKGTFAALSELHCDKLHVDPENFRLLGNVLVVVLARHFGKDFTPELQASYQKVVAGVANALAHKYH------"));
		solution.addSequence(new Sequence("--------VHLTPEEKSAVTALWGKV--NVDEVGGEALGRLLVVYPWTQRFFESFGDLSTPDAVMGNPKVKAHGKKVLGAFSDGLAHLDN-----LKGTFATLSELHCDKLHVDPENFRLLGNVLVCVLAHHFGKEFTPPVQAAYQKVVAGVANALAHKYH------"));
		return solution;
	}
	
	public String[] getAAGrowthHormoneSequences()
	{		
		//>gi|1432171|gb|AAB04025.1| presomatotropin [Rattus norvegicus]
		String s1 = "MAADSQTPWLLTFSLLCLLWPQEAGALPAMPLSSLFANAVLRAQHLHQLAADTYKEFERAYIPEGQRYSIQNAQAAFCFSETIPAPTGKEEAQQRTDMELLRFSLLLIQSWLGPVQFLSRIFTNSLMFGTSDRVYEKLKDLEEGIQALMQELEDGSPRIGQILKQTYDKFDANMRSDDALLKNYGLLSCFKKDLHKAETYLRVMKCRRFAESSCAF";
		//>gi|5452944|gb|AAD43366.1|AF069071_1 growth hormone [Canis familiaris]
		String s2 = "MAASPRNSVLLAFALLCLPWPQEVGAFPAMPLSSLFANAVLRAQHLHQLAADTYKEFERAYIPEGQRYSIQNAQAAFCFSETIPAPTGKDEAQQRSDVELLRFSLLLIQSWLGPVQFLSRVFTNSLVFGTSDRVYEKLKDLEEGIQALMRELEDGSPRAGQILKQTYDKFDTNLRSDDALLKNYGLLSCFKKDLHKAETYLRVMKCRRFVESSCAF";
		//>gi|825769|gb|AAA67294.1| growth hormone [Felis catus]
		String s3 = "MAAGPRNSVLLAFALLCLPWPQEVGTFPAMPLSSLFANAVLRAQHLHQLAADTYKEFERAYIPEGQRYSIQNAQAAFCFSETIPAPTGKDEAQQRSDVELLRFSLLLIQSWLGPVQFLSRVFTNSLVFGTSDRVYEKLKDLEEGIQALMRELEDGSPRGGQILKQTYDKFDTNLRSDDALLKNYGLLSCFKKDLHKAETYLRVMKCRRFVESSCAF";
		//>gi|409963|gb|AAA21027.1| growth hormone [Equus caballus]
		String s4 = "MAAGPRTSVLLAFGLLCLPWPQDVGAFPAMPLSSLFANAVLRAQHLHQLAADTYKEFERAYIPEGQRYSIQNAQAAFCFSETIPAPTGKDEAQQRSDMELLRFSLLLIQSWLGPVQLLSRVFTNSLVFGTSDRVYEKLRDLEEGIQALMRELEDGSPRAGQILKQTYDKFDTNLRSDDALLKNYGLLSCFKKDLHKAETYLRVMKCRRFVESSCAF";
		//>gi|558683|emb|CAA86287.1| growth hormone [Oryctolagus cuniculus]
		String s5 = "MAAGSWTAGLLAFALLCLPWPQEASAFPAMPLSSLFANAVLRAQHLHQLAADTYKEFERAYIPEGQRYSIQNAQAAFCFSETIPAPTGKDEAQQRSDMELLRFSLLLIQSWLGPVQFLSRAFTNTLVFGTSDRVYEKLKDLEEGIQALMRELEDGSPRVGQLLKQTYDKFDTNLRGDDALLKNYGLLSCFKKDLHKAETYLRVMKCRRFVESSCVF";
		//>gi|32452169|emb|CAE01391.1| growth hormone [Camelus dromedarius]
		String s6 = "MAAGPRTSVLLAFTLLCLPWPQEAGAFPAMPLSSLFANAVLRAQHLHQLAADTYKEFERTYIPEGQRYSIQNAQAAFCFSETIPAPTGKDEAQQRSDVELLRFSLLLIQSWLGPVQFLSRVFTNSLVFGTSDRVYEKLKDLEEGIQALMRELEDGSPRAGQILRQTYDKFDTNLRSDDALLKNYGLLSCFKKDLHKAETYLRVMKCRRFVESSCAF";
		//>gi|46361729|gb|AAS89356.1| growth hormone [Sus scrofa]
		String s7 = "MAAGPRTSVLLAFALLCLPWTQEVGAFPAMPLSSLFANAVLRAQHLHQLAADTYKEFERAYIPEGQRYSIQNAQAAFCFSETIPAPTGKDEAQQRSDVELLRFSLLLIQSWLGPVQFLSRVFTNSLVFGTSDRVYEKLKDLEEGIQALMRELEDGSPRAGQILKQTYDKFDTNLRSDDALLKNYGLLSCFKKDLHKAETYLRVMKCRRFVESSCAF";
		//>gi|21698804|emb|CAD37292.1| growth hormone [Delphinus delphis]
		String s8 = "MAAGPRTSMLLAFALLCLPWTQEVGAFPAMPLSSLFANAVLRAQHLHQLAADTYKEFERAYIPEGQRYSIQNTQAAFCFSETIPAPTGKDEAQQRSDVELLRFSLLLIQSWLGPVQFLSRVFTNSLVFGTSDRVYEKLKDLEEGIQALMRELEDGSPRAGQILKQTYDKFDTNMRSDDALLKNYGLLSCFKKDLHKAETYLRVMKCRRFVESSCAF";
		//>gi|32452339|emb|CAE01393.1| growth hormone [Giraffa camelopardalis]
		String s9 = "MMAAGPRTSLLLAFALLCLPWTQMVGAFPAMSLSGLFANAVLRAQHLHQLAADTFKEFERTYIPEGQRYSIQNTQVAFCFSETIPAPTGKNEAQQKSDLELLRISLLLIQSWLGPLQFLSRVFSNSLVFGTSDRVYEKLKDLEEGILALMRELEDGTPRAGQILKQTYDKFDTNMRSDDALLKNYGLLSCFRKDLHKTETYLRVMKCRRFGEASCAF";
		//>gi|312406|emb|CAA23779.1| growth hormone [Homo sapiens]
		String s10 = "MATGSRTSLLLAFGLLCLPWLQEGSAFPTIPLSRLFDNASLRAHRLHQLAFDTYQEFEEAYIPKEQKYSFLQNPQTSLCFSESIPTPSNREETQQKSNLELLRISLLLIQSWLEPVQFLRSVFANSLVYGASDSNVYDLLKDLEEGIQTLMGRLEDGSPRTGQIFKQTYSKFDTNSHNDDALLKNYGLLYCFRKDMDKVETFLRIVQCRSVEGSCGF";
		
		String[] inputSequences = {s1, s2, s3, s4, s5, s6, s7, s8, s9, s10};
		return inputSequences;
	}
	
	public Alignment getAAGrowthHormoneClustalWSolution()
	{		
		Alignment solution = new Alignment();
		solution.addSequence(new Sequence("-MAASPRNSVLLAFALLCLPWPQEVGAFPAMPLSSLFANAVLRAQHLHQLAADTYKEFERAYIPEGQRYS-IQNAQAAFCFSETIPAPTGKDEAQQRSDVELLRFSLLLIQSWLGPVQFLSRVFTNSLVFGTSDR-VYEKLKDLEEGIQALMRELEDGSPRAGQILKQTYDKFDTNLRSDDALLKNYGLLSCFKKDLHKAETYLRVMKCRRFVESSCAF"));
		solution.addSequence(new Sequence("-MAAGPRNSVLLAFALLCLPWPQEVGTFPAMPLSSLFANAVLRAQHLHQLAADTYKEFERAYIPEGQRYS-IQNAQAAFCFSETIPAPTGKDEAQQRSDVELLRFSLLLIQSWLGPVQFLSRVFTNSLVFGTSDR-VYEKLKDLEEGIQALMRELEDGSPRGGQILKQTYDKFDTNLRSDDALLKNYGLLSCFKKDLHKAETYLRVMKCRRFVESSCAF"));
		solution.addSequence(new Sequence("-MAADSQTPWLLTFSLLCLLWPQEAGALPAMPLSSLFANAVLRAQHLHQLAADTYKEFERAYIPEGQRYS-IQNAQAAFCFSETIPAPTGKEEAQQRTDMELLRFSLLLIQSWLGPVQFLSRIFTNSLMFGTSDR-VYEKLKDLEEGIQALMQELEDGSPRIGQILKQTYDKFDANMRSDDALLKNYGLLSCFKKDLHKAETYLRVMKCRRFAESSCAF"));
		solution.addSequence(new Sequence("-MAAGSWTAGLLAFALLCLPWPQEASAFPAMPLSSLFANAVLRAQHLHQLAADTYKEFERAYIPEGQRYS-IQNAQAAFCFSETIPAPTGKDEAQQRSDMELLRFSLLLIQSWLGPVQFLSRAFTNTLVFGTSDR-VYEKLKDLEEGIQALMRELEDGSPRVGQLLKQTYDKFDTNLRGDDALLKNYGLLSCFKKDLHKAETYLRVMKCRRFVESSCVF"));
		solution.addSequence(new Sequence("-MAAGPRTSVLLAFTLLCLPWPQEAGAFPAMPLSSLFANAVLRAQHLHQLAADTYKEFERTYIPEGQRYS-IQNAQAAFCFSETIPAPTGKDEAQQRSDVELLRFSLLLIQSWLGPVQFLSRVFTNSLVFGTSDR-VYEKLKDLEEGIQALMRELEDGSPRAGQILRQTYDKFDTNLRSDDALLKNYGLLSCFKKDLHKAETYLRVMKCRRFVESSCAF"));
		solution.addSequence(new Sequence("-MAAGPRTSVLLAFGLLCLPWPQDVGAFPAMPLSSLFANAVLRAQHLHQLAADTYKEFERAYIPEGQRYS-IQNAQAAFCFSETIPAPTGKDEAQQRSDMELLRFSLLLIQSWLGPVQLLSRVFTNSLVFGTSDR-VYEKLRDLEEGIQALMRELEDGSPRAGQILKQTYDKFDTNLRSDDALLKNYGLLSCFKKDLHKAETYLRVMKCRRFVESSCAF"));
		solution.addSequence(new Sequence("-MAAGPRTSVLLAFALLCLPWTQEVGAFPAMPLSSLFANAVLRAQHLHQLAADTYKEFERAYIPEGQRYS-IQNAQAAFCFSETIPAPTGKDEAQQRSDVELLRFSLLLIQSWLGPVQFLSRVFTNSLVFGTSDR-VYEKLKDLEEGIQALMRELEDGSPRAGQILKQTYDKFDTNLRSDDALLKNYGLLSCFKKDLHKAETYLRVMKCRRFVESSCAF"));
		solution.addSequence(new Sequence("-MAAGPRTSMLLAFALLCLPWTQEVGAFPAMPLSSLFANAVLRAQHLHQLAADTYKEFERAYIPEGQRYS-IQNTQAAFCFSETIPAPTGKDEAQQRSDVELLRFSLLLIQSWLGPVQFLSRVFTNSLVFGTSDR-VYEKLKDLEEGIQALMRELEDGSPRAGQILKQTYDKFDTNMRSDDALLKNYGLLSCFKKDLHKAETYLRVMKCRRFVESSCAF"));
		solution.addSequence(new Sequence("MMAAGPRTSLLLAFALLCLPWTQMVGAFPAMSLSGLFANAVLRAQHLHQLAADTFKEFERTYIPEGQRYS-IQNTQVAFCFSETIPAPTGKNEAQQKSDLELLRISLLLIQSWLGPLQFLSRVFSNSLVFGTSDR-VYEKLKDLEEGILALMRELEDGTPRAGQILKQTYDKFDTNMRSDDALLKNYGLLSCFRKDLHKTETYLRVMKCRRFGEASCAF"));
		solution.addSequence(new Sequence("-MATGSRTSLLLAFGLLCLPWLQEGSAFPTIPLSRLFDNASLRAHRLHQLAFDTYQEFEEAYIPKEQKYSFLQNPQTSLCFSESIPTPSNREETQQKSNLELLRISLLLIQSWLEPVQFLRSVFANSLVYGASDSNVYDLLKDLEEGIQTLMGRLEDGSPRTGQIFKQTYSKFDTNSHNDDALLKNYGLLYCFRKDMDKVETFLRIVQCR-SVEGSCGF"));
		return solution;
	}

}